
name: acr-login

on:
  push:
    branches:
      - main
      - feature/*

    paths:
      - 'workfolder/**'

  workflow_dispatch:
  pull_request:
    branches:
      - main
      - feature/*

  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  contents: read
  pull-requests: write
  id-token: write
  issues: write
  checks: write

jobs:
  build:
    name: Drebaba
    runs-on: [self-hosted, linux] 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker login
        uses: azure/docker-login@v2
        with:
          login-server: acrdrecac.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
       
      - name: check nmaeserver
        run: |
          cat /etc/resolv.conf
          sudo systemctl status docker

